version: "2"
services:
  web:
    build: .
    container_name: node_app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - "./data/db:/mongo/db/data"

  mongo-express:
      image: mongo-express:latest
      links:
        - mongo:mongo
      ports:
        - '27018:8081'